name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Node.js (for JS/TS analysis)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install PHP (for PHP analysis)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Install SonarQube Scanner
        run: npm install -g sonar-scanner

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=sqp_32c39ca903ebf4145095d08f9886459723457a4d \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN 